name: maktampos
description: Maktam POS app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  intl: ^0.17.0
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3
  flutter_svg: ^1.0.3
  shimmer: ^2.0.0
  lazy_load_scrollview: ^1.3.0
  material_dialogs: ^1.1.1
  smart_select: ^4.3.2
  flutter_downloader: ^1.7.1
  pull_to_refresh: ^2.0.0
  alice_lightweight: ^3.0.0
  shake: ^2.0.0
  flutter_staggered_grid_view: ^0.6.1
  uc_pdfview: ^0.0.3
  websafe_svg: ^2.1.1
  dio_http_cache: ^0.3.0
  flutter_inappwebview: ^5.3.2
  permission_handler: ^8.3.0
  path_provider: ^2.0.8
  android_path_provider: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Icons/
    - assets/images/